# Generated by Django 5.2.1 on 2025-05-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_small', models.TextField()),
                ('text_great', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('facebook', models.URLField()),
                ('telegram', models.URLField()),
                ('whatsapp', models.URLField()),
                ('instagram', models.URLField()),
                ('twitter', models.URLField()),
                ('youtube', models.URLField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.JSONField(default={'lat': 35.6950394, 'lng': 51.3743092})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('news_letter', models.TextField()),
                ('copy_right', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeaderObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=100)),
                ('childern', models.ManyToManyField(blank=True, to='website.headerobject')),
            ],
        ),
    ]
