# Generated by Django 5.2.1 on 2025-05-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='location',
        ),
        migrations.AddField(
            model_name='contactus',
            name='location_latitude',
            field=models.FloatField(default=35.6950394),
        ),
        migrations.AddField(
            model_name='contactus',
            name='location_longitude',
            field=models.FloatField(default=51.3743092),
        ),
    ]
