# Generated by Django 5.2.1 on 2025-05-19 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_remove_contactus_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerobject',
            name='childern',
        ),
        migrations.AddField(
            model_name='headerobject',
            name='is_childern',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='headerobject',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.headerobject'),
        ),
    ]
