# Generated by Django 5.2.1 on 2025-05-19 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_headerobject_childern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='headerobject',
            name='is_childern',
            field=models.BooleanField(default=False),
        ),
    ]
