# Generated by Django 5.2.1 on 2025-05-19 12:51

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_webinfo_video_file_alter_headerobject_is_childern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='text_small',
            new_name='about_us_small',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='text_great',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default=True, null=True, verbose_name='Text'),
        ),
    ]
