# Generated by Django 5.2.1 on 2025-05-20 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_text_small_aboutus_about_us_small_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='assistent_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='headerobject',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childern', to='website.headerobject'),
        ),
    ]
