# Generated by Django 5.2.1 on 2025-05-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_contactus_assistent_number_alter_headerobject_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerobject',
            name='href',
            field=models.CharField(max_length=1000),
        ),
    ]
