# Generated by Django 5.2.1 on 2025-05-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_headerobject_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerobject',
            name='dynamic_part',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
