# Generated by Django 5.2.1 on 2025-05-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_headerobject_dynamic_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='logo_down',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
    ]
