# Generated by Django 5.2.1 on 2025-05-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_webinfo_logo_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='index_banner_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
