# Generated by Django 5.2.1 on 2025-05-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_webinfo_index_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinfo',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to='thumbnails/'),
        ),
    ]
