# Generated by Django 5.2.1 on 2025-05-22 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_webinfo_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/advertising/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('content', models.TextField()),
            ],
        ),
    ]
