# Generated by Django 5.2.1 on 2025-05-19 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_flight_beginning_time_flight_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.tourgroup'),
        ),
    ]
