# Generated by Django 5.2.1 on 2025-05-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('tour', '0004_tour_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='hotell',
            field=models.ManyToManyField(to='hotel.hotel'),
        ),
    ]
