# Generated by Django 5.2.1 on 2025-05-20 12:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_tour_hotell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='beginning_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='flight',
        ),
        migrations.AddField(
            model_name='flight',
            name='reach_hour',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='start_hour',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tour',
            name='flight_go',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_go', to='tour.flight'),
        ),
        migrations.AddField(
            model_name='tour',
            name='flight_return',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_return', to='tour.flight'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tour.tags'),
        ),
    ]
