# Generated by Django 5.2.1 on 2025-05-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_tags_remove_flight_beginning_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tagss',
        ),
    ]
