# Generated by Django 5.2.1 on 2025-05-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_service_hotel'),
        ('tour', '0007_rename_tags_tagss'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='tour/single-tour/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='hotell',
            field=models.ManyToManyField(related_name='tourss', to='hotel.hotel'),
        ),
    ]
