# Generated by Django 5.2.1 on 2025-05-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_tour_image_alter_tour_hotell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(null=True, upload_to='tour/single-tour/'),
        ),
    ]
