# Generated by Django 5.2.1 on 2025-05-22 11:09

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_alter_service_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourgroup',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tour.tagss'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtours', to='tour.tourgroup'),
        ),
        migrations.AlterField(
            model_name='tourgroup',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
