# Generated by Django 5.2.1 on 2025-05-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_tourgroup_tags_alter_tour_tour_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion_pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tours', models.ManyToManyField(to='tour.tour')),
            ],
        ),
    ]
