# Generated by Django 5.2.1 on 2025-05-22 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_suggestion_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='ratings',
            field=models.ManyToManyField(blank=True, editable=False, to='tour.rating'),
        ),
    ]
