# Generated by Django 5.2.1 on 2025-05-28 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0016_alter_comment_is_reply_alter_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourgroup',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 28, 8, 32, 46, 819921, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
