# Generated by Django 5.2.1 on 2025-05-19 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created_date_alter_post_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='other_site',
            new_name='link_to_other_site',
        ),
    ]
