# Generated by Django 5.2.1 on 2025-05-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_other_site_post_link_to_other_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
