# Generated by Django 5.2.1 on 2025-05-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.BooleanField(default=True),
        ),
    ]
