# Generated by Django 5.2.1 on 2025-05-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='linkdin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='twitter',
            field=models.URLField(null=True),
        ),
    ]
