# Generated by Django 5.2.1 on 2025-05-20 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_facebook_post_instagram_post_linkdin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to='blog.post'),
        ),
    ]
