# Generated by Django 5.2.1 on 2025-05-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_is_reply_comment_reply_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_reply',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
