# Generated by Django 5.2.1 on 2025-05-20 12:03

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_pictures_hotel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='data_image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='service',
            field=models.ImageField(blank=True, null=True, upload_to='service/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='service_low',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='service/low/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='service_medium',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='service/medium/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='main_image',
            field=models.ImageField(upload_to='hotel/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='hotel/album'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
