# Generated by Django 5.2.1 on 2025-05-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_hotel_data_image_hotel_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='pictures',
        ),
        migrations.AddField(
            model_name='hotel',
            name='picture1',
            field=models.ImageField(null=True, upload_to='hotel/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='picture2',
            field=models.ImageField(null=True, upload_to='hotel/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='picture3',
            field=models.ImageField(null=True, upload_to='hotel/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='picture4',
            field=models.ImageField(null=True, upload_to='hotel/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='picture5',
            field=models.ImageField(null=True, upload_to='hotel/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='picture6',
            field=models.ImageField(null=True, upload_to='hotel/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='main_image',
            field=models.ImageField(null=True, upload_to='hotel/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
