# Generated by Django 5.2.1 on 2025-05-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_hotel_pictures_hotel_picture1_hotel_picture2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='picture7',
            field=models.ImageField(null=True, upload_to='hotel/'),
        ),
    ]
