# Generated by Django 5.2.1 on 2025-05-21 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_picture7'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotelll', to='hotel.hotel')),
            ],
        ),
    ]
