# Generated by Django 5.2.1 on 2025-05-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_service_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='breakfast',
            field=models.BooleanField(default=True),
        ),
    ]
