# Generated by Django 5.2.1 on 2025-05-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_hotel_breakfast'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.PositiveIntegerField(default=100000),
        ),
    ]
